# This file was generated by GoReleaser. DO NOT EDIT.
cask "gk" do
  version "0.62.1"

  on_macos do
    on_intel do
      sha256 "18a90ce314167de388f9749cd581f82465fc2463efe49aaa3a9a2f6e06e47197"
      url "https://github.com/x-mesh/gk/releases/download/v#{version}/gk_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0efb698a2b7ee41ff79026d241775bd7b71f1690c1bebc3f597279632bc4b700"
      url "https://github.com/x-mesh/gk/releases/download/v#{version}/gk_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "153165011817c9b469a8effbec6987db1fd8f13f3ab68eef08046f4b33ece319"
      url "https://github.com/x-mesh/gk/releases/download/v#{version}/gk_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f44225342cb6ed392e3d912c0100f37c32db48be87ad972e9b39363485cdaf9f"
      url "https://github.com/x-mesh/gk/releases/download/v#{version}/gk_linux_arm64.tar.gz"
    end
  end

  name "gk"
  desc "Lightweight Go git helper CLI (pull, log, status, branch)"
  homepage "https://github.com/x-mesh/gk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gk"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gk"]
  end

  # No zap stanza required

  caveats <<~EOS
    gk uses git under the hood. Ensure git >= 2.30 is installed.
  EOS
end
