# This file was generated by GoReleaser. DO NOT EDIT.
cask "gk" do
  binary "gk", target: "git-kit"

  version "0.113.0"

  on_macos do
    on_intel do
      sha256 "762c50ecf591ef718f34291bfaece939e7eb5df8fb63aea19580dbb5a30f46bf"
      url "https://github.com/x-mesh/gk/releases/download/v#{version}/gk_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "046d719c4504aecfb723d23e94368f99af6d07d11919bc3111132c1c3138c110"
      url "https://github.com/x-mesh/gk/releases/download/v#{version}/gk_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3a71ea788a4f1f4529dbf24c9575299e06871a4b2098d90f6a6ca04078b90b34"
      url "https://github.com/x-mesh/gk/releases/download/v#{version}/gk_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a0a57118daefbff24584708651f73b3941a5068251a0a413072469eeb4c8c121"
      url "https://github.com/x-mesh/gk/releases/download/v#{version}/gk_linux_arm64.tar.gz"
    end
  end

  name "gk"
  desc "Lightweight Go git helper CLI (pull, log, status, branch)"
  homepage "https://github.com/x-mesh/gk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gk"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gk"]
  end

  # No zap stanza required

  caveats <<~EOS
    gk uses git under the hood. Ensure git >= 2.30 is installed.
  EOS
end
