# This file was generated by GoReleaser. DO NOT EDIT.
cask "gk" do
  binary "gk", target: "git-kit"

  version "0.72.0"

  on_macos do
    on_intel do
      sha256 "d05745c8fe3d9655d99ecdb0fd745da89bced0e8754c9a662ce38a71c2609729"
      url "https://github.com/x-mesh/gk/releases/download/v#{version}/gk_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e2fc5ec0686868f271d3cd6013a01de359489a7bfac7046d97d87e8728c2cb73"
      url "https://github.com/x-mesh/gk/releases/download/v#{version}/gk_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bed897a0c8fd169936ad8c277a7d8b33c41c368785263744d4835294e14750e8"
      url "https://github.com/x-mesh/gk/releases/download/v#{version}/gk_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "373d368d18cda11b54c7385208396adadf13cedfa52956a20691a245b982e45c"
      url "https://github.com/x-mesh/gk/releases/download/v#{version}/gk_linux_arm64.tar.gz"
    end
  end

  name "gk"
  desc "Lightweight Go git helper CLI (pull, log, status, branch)"
  homepage "https://github.com/x-mesh/gk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gk"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gk"]
  end

  # No zap stanza required

  caveats <<~EOS
    gk uses git under the hood. Ensure git >= 2.30 is installed.
  EOS
end
