# This file is generated by the httprove release workflow. DO NOT EDIT.
cask "httprove" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "8809243b330830e3d78c2f30febecf50b03b1bf61219873b8e3fbb131c5684ef"
      url "https://github.com/x-mesh/httprove/releases/download/v#{version}/httprove_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ef7fb0179f0400e493b5229b6e0a852d83b3212be028674c91e9763c7364f078"
      url "https://github.com/x-mesh/httprove/releases/download/v#{version}/httprove_darwin_amd64.tar.gz"
    end
  end

  on_linux do
    on_arm do
      sha256 "6e238c90b74479ef9098bffc10efd5ae0d56cab66f0caba20f346cb9a350426c"
      url "https://github.com/x-mesh/httprove/releases/download/v#{version}/httprove_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2a36947a5ab979ce9944a6ddc8a1d8ddecdd4ee40a5cb1f662f4640470cda8d7"
      url "https://github.com/x-mesh/httprove/releases/download/v#{version}/httprove_linux_amd64.tar.gz"
    end
  end

  name "httprove"
  desc "HTTP(S) service diagnostics for SREs: latency waterfall, TLS inspection, TUI"
  homepage "https://github.com/x-mesh/httprove"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "httprove"
  # 단축 명령 hpr 를 같은 바이너리로 노출.
  binary "httprove", target: "hpr"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/httprove"]
  end

  caveats <<~CAVEAT
    Two commands are installed: httprove (primary) and hpr (alias).
    Run 'httprove update' to self-update.
  CAVEAT
end
