# This file is generated by the httprove release workflow. DO NOT EDIT.
cask "httprove" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "a4103b9fb7d1ec4464da7eaf54d1fd5804eb4ab01f1cc4136c8250ded0c27006"
      url "https://github.com/x-mesh/httprove/releases/download/v#{version}/httprove_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fb0a13a6b2ecff904c0c586880b932599e3e03cefb2f621c558f3d270632a712"
      url "https://github.com/x-mesh/httprove/releases/download/v#{version}/httprove_darwin_amd64.tar.gz"
    end
  end

  on_linux do
    on_arm do
      sha256 "008e4f4e2d4355a753dbb47c69f6429e4a8da069ce649b2837b9e18068b3f4d4"
      url "https://github.com/x-mesh/httprove/releases/download/v#{version}/httprove_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b0096deaf9e820ba9671c3abee807a5cee000fa8348c5ea3456d154c2361ea5d"
      url "https://github.com/x-mesh/httprove/releases/download/v#{version}/httprove_linux_amd64.tar.gz"
    end
  end

  name "httprove"
  desc "HTTP(S) service diagnostics for SREs: latency waterfall, TLS inspection, TUI"
  homepage "https://github.com/x-mesh/httprove"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "httprove"
  # 단축 명령 hpr 를 같은 바이너리로 노출.
  binary "httprove", target: "hpr"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/httprove"]
  end

  caveats <<~CAVEAT
    Two commands are installed: httprove (primary) and hpr (alias).
    Run 'httprove update' to self-update.
  CAVEAT
end
