# This file is generated by the httprove release workflow. DO NOT EDIT.
cask "httprove" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "566861d95194fdfd5b8da60368deea9b56c106b37ca2979065a5d64fade45cf1"
      url "https://github.com/x-mesh/httprove/releases/download/v#{version}/httprove_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "73576e722b72c772856340955d79d1829a901fd88176bad120d84ad2b1c7cc2f"
      url "https://github.com/x-mesh/httprove/releases/download/v#{version}/httprove_darwin_amd64.tar.gz"
    end
  end

  on_linux do
    on_arm do
      sha256 "f6c3923393f610cbe1e339c92ceecf3e77b59234446f7133036da1c8259a028d"
      url "https://github.com/x-mesh/httprove/releases/download/v#{version}/httprove_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "70468b75cc0708a6b99406b67135459dcc24e21ab68d75ef045ec72fe6400f3e"
      url "https://github.com/x-mesh/httprove/releases/download/v#{version}/httprove_linux_amd64.tar.gz"
    end
  end

  name "httprove"
  desc "HTTP(S) service diagnostics for SREs: latency waterfall, TLS inspection, TUI"
  homepage "https://github.com/x-mesh/httprove"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "httprove"
  # 단축 명령 hpr 를 같은 바이너리로 노출.
  binary "httprove", target: "hpr"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/httprove"]
  end

  caveats <<~CAVEAT
    Two commands are installed: httprove (primary) and hpr (alias).
    Run 'httprove update' to self-update.
  CAVEAT
end
