# This file is generated by the space-mesh release workflow. DO NOT EDIT.
cask "space-mesh" do
  version "0.3.0"

  on_arm do
    sha256 "bc3534b851a1cdd057b7c8628548267cf9839c14fe5d434e57971e51fc66163d"

    url "https://github.com/x-mesh/space-mesh/releases/download/v#{version}/space-mesh-macos-#{version}-arm64.zip"
  end
  on_intel do
    sha256 "06731dbec90ba14d834672642e7c93814afe6123207eb0c79f3177e6bb445fc3"

    url "https://github.com/x-mesh/space-mesh/releases/download/v#{version}/space-mesh-macos-#{version}-x86_64.zip"
  end

  name "space-mesh"
  desc "Disk space analyzer with treemap, cleanup guidance, and incremental scanning"
  homepage "https://github.com/x-mesh/space-mesh"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: :sonoma

  app "space-mesh.app"
  binary "#{appdir}/space-mesh.app/Contents/Resources/space-mesh"

  preflight do
    system_command "/usr/bin/osascript",
                   args:         ["-e", 'tell application "space-mesh" to quit'],
                   must_succeed: false
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/space-mesh.app"],
                   sudo: false
  end

  zap trash: [
    "~/Library/Application Support/space-mesh",
    "~/Library/Preferences/com.x-mesh.space-mesh.plist",
    "~/Library/Saved Application State/com.x-mesh.space-mesh.savedState",
  ]

  caveats <<~CAVEATS
    space-mesh is distributed with ad-hoc signing and without Apple notarization.
    This cask removes the quarantine attribute after installation.

    The bundled space-mesh CLI is linked to #{HOMEBREW_PREFIX}/bin.
  CAVEATS
end
