# This file is generated by the space-mesh release workflow. DO NOT EDIT.
cask "space-mesh" do
  version "0.5.1"

  on_arm do
    sha256 "dd11b5bb932212e164bad62493b80714dfb3b9d4857e3cf67be8ef059903d5bb"

    url "https://github.com/x-mesh/space-mesh/releases/download/v#{version}/space-mesh-macos-#{version}-arm64.zip"
  end
  on_intel do
    sha256 "e64f7d762eac1b596761c523f4429499ef1e57b3627b86f4f8fdd2a5b5d0827a"

    url "https://github.com/x-mesh/space-mesh/releases/download/v#{version}/space-mesh-macos-#{version}-x86_64.zip"
  end

  name "space-mesh"
  desc "Disk space analyzer with treemap, cleanup guidance, and incremental scanning"
  homepage "https://github.com/x-mesh/space-mesh"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: :sonoma

  app "space-mesh.app"
  binary "#{appdir}/space-mesh.app/Contents/Resources/space-mesh"

  preflight do
    system_command "/usr/bin/osascript",
                   args:         ["-e", 'tell application "space-mesh" to quit'],
                   must_succeed: false
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/space-mesh.app"],
                   sudo: false
  end

  zap trash: [
    "~/Library/Application Support/space-mesh",
    "~/Library/Preferences/com.x-mesh.space-mesh.plist",
    "~/Library/Saved Application State/com.x-mesh.space-mesh.savedState",
  ]

  caveats <<~CAVEATS
    space-mesh is distributed with ad-hoc signing and without Apple notarization.
    This cask removes the quarantine attribute after installation.

    The bundled space-mesh CLI is linked to #{HOMEBREW_PREFIX}/bin.
  CAVEATS
end
