# This file is generated by the space-mesh release workflow. DO NOT EDIT.
cask "space-mesh" do
  version "0.2.0"

  on_arm do
    sha256 "2a8e16bf055ac6017338c8b048d0b807b34aeeb6d007947c36666c77952ac384"

    url "https://github.com/x-mesh/space-mesh/releases/download/v#{version}/space-mesh-macos-#{version}-arm64.zip"
  end
  on_intel do
    sha256 "d3d75b75098296d1d696e81f9939833e8e9f09f4e43bf8c8644aac7a02ac0a63"

    url "https://github.com/x-mesh/space-mesh/releases/download/v#{version}/space-mesh-macos-#{version}-x86_64.zip"
  end

  name "space-mesh"
  desc "Disk space analyzer with treemap, cleanup guidance, and incremental scanning"
  homepage "https://github.com/x-mesh/space-mesh"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: :sonoma

  app "space-mesh.app"
  binary "#{appdir}/space-mesh.app/Contents/Resources/space-mesh"

  preflight do
    system_command "/usr/bin/osascript",
                   args:         ["-e", 'tell application "space-mesh" to quit'],
                   must_succeed: false
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/space-mesh.app"],
                   sudo: false
  end

  zap trash: [
    "~/Library/Application Support/space-mesh",
    "~/Library/Preferences/com.x-mesh.space-mesh.plist",
    "~/Library/Saved Application State/com.x-mesh.space-mesh.savedState",
  ]

  caveats <<~CAVEATS
    space-mesh is distributed with ad-hoc signing and without Apple notarization.
    This cask removes the quarantine attribute after installation.

    The bundled space-mesh CLI is linked to #{HOMEBREW_PREFIX}/bin.
  CAVEATS
end
