# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aic < Formula
  desc "Shell command error analyzer with LLM (PTY wrapper + supervisor daemon)"
  homepage "https://github.com/x-mesh/aic"
  version "0.24.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/x-mesh/aic/releases/download/v0.24.0/aic_0.24.0_darwin_amd64.tar.gz"
      sha256 "81800ac18ca56d262fdebd56e59012d4720dc7f0a30bd07f104fb8254a45e4c3"

      define_method(:install) do
        bin.install "aic"
        bin.install "aic-session"
        bin.install "aicd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/x-mesh/aic/releases/download/v0.24.0/aic_0.24.0_darwin_arm64.tar.gz"
      sha256 "810f94597c16e6464773684d198d00d3f5b39b7bcd2b62cf0e55726bf4c5625f"

      define_method(:install) do
        bin.install "aic"
        bin.install "aic-session"
        bin.install "aicd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/x-mesh/aic/releases/download/v0.24.0/aic_0.24.0_linux_amd64.tar.gz"
      sha256 "0a0c77ba9966c00fa347a9be8c4aa90cee41f59d1df604626a1a053c67dc45ca"
      define_method(:install) do
        bin.install "aic"
        bin.install "aic-session"
        bin.install "aicd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/x-mesh/aic/releases/download/v0.24.0/aic_0.24.0_linux_arm64.tar.gz"
      sha256 "70a141c1c4ce32d886beabd292e6b1799f62b3f534dcf36b86f6d6322f1dc6d7"
      define_method(:install) do
        bin.install "aic"
        bin.install "aic-session"
        bin.install "aicd"
      end
    end
  end

  def caveats
    <<~EOS
      To run aicd in the background and on login:

        aic daemon install        # writes the right unit for your OS

      What this does:
        macOS  -> ~/Library/LaunchAgents/com.x-mesh.aicd.plist (launchctl)
        Linux  -> ~/.config/systemd/user/aicd.service (systemctl --user)

      First-time setup:
        aic config                # interactive provider/api_key/model wizard
        aic init zsh              # add 'source ~/.aic/hooks.zsh' to your rc
    EOS
  end

  test do
    system "#{bin}/aic", "--version"
    system "#{bin}/aic-session", "--version"
    system "#{bin}/aicd", "--version"
  end
end
