# typed: false
# frozen_string_literal: true

# This file is generated by aic's release workflow. DO NOT EDIT.
class Aic < Formula
  desc "Shell command error analyzer with LLM (PTY wrapper + supervisor daemon)"
  homepage "https://github.com/x-mesh/aic"
  version "0.50.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/x-mesh/aic/releases/download/v0.50.9/aic_0.50.9_darwin_amd64.tar.gz"
      sha256 "ec2673ebdeeb6b74a0b6eb95b3931a98474bdaf9d396976247e37924a9921ffa"

      def install
        bin.install "aic"
        bin.install "aic-session"
        bin.install "aicd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/x-mesh/aic/releases/download/v0.50.9/aic_0.50.9_darwin_arm64.tar.gz"
      sha256 "446b8d5f8e6d07fa4aae9fc6284df8353b59f7d5fc8a4cecef2c3fcaa37af290"

      def install
        bin.install "aic"
        bin.install "aic-session"
        bin.install "aicd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/x-mesh/aic/releases/download/v0.50.9/aic_0.50.9_linux_amd64.tar.gz"
      sha256 "0befa64bc20c2e3e70d57bb91ecd938191da813118c9c1dfacd8bdc94dbcec49"

      def install
        bin.install "aic"
        bin.install "aic-session"
        bin.install "aicd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/x-mesh/aic/releases/download/v0.50.9/aic_0.50.9_linux_arm64.tar.gz"
      sha256 "4f79835c558617e371988b87f8583488c7407f8346d4ecbabe5971384bfc021b"

      def install
        bin.install "aic"
        bin.install "aic-session"
        bin.install "aicd"
      end
    end
  end

  def caveats
    <<~EOS
      To run aicd in the background and on login:

        aic daemon install        # writes the right unit for your OS

      First-time setup:
        aic config                # interactive provider/api_key/model wizard
        aic init zsh              # add 'source ~/.aic/hooks.zsh' to your rc
    EOS
  end

  test do
    system "#{bin}/aic", "--version"
    system "#{bin}/aic-session", "--version"
    system "#{bin}/aicd", "--version"
  end
end
