# typed: false
# frozen_string_literal: true

# This file is generated by aic's release workflow. DO NOT EDIT.
class Aic < Formula
  desc "Shell command error analyzer with LLM (PTY wrapper + supervisor daemon)"
  homepage "https://github.com/x-mesh/aic"
  version "0.50.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/x-mesh/aic/releases/download/v0.50.12/aic_0.50.12_darwin_amd64.tar.gz"
      sha256 "54c6a9804696cad56626e9b321967977684c4bd72531bca6bd0b3c4192572d5d"

      def install
        bin.install "aic"
        bin.install "aic-session"
        bin.install "aicd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/x-mesh/aic/releases/download/v0.50.12/aic_0.50.12_darwin_arm64.tar.gz"
      sha256 "faa545ef06b6bf09ab9a1c61f7d75916b98a6f5cf37d42148abb0f80b1fb5c92"

      def install
        bin.install "aic"
        bin.install "aic-session"
        bin.install "aicd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/x-mesh/aic/releases/download/v0.50.12/aic_0.50.12_linux_amd64.tar.gz"
      sha256 "a4bc32f41d13465a52f577e6f8c168acf44a6e7ce32b5d1be9b54faad0089136"

      def install
        bin.install "aic"
        bin.install "aic-session"
        bin.install "aicd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/x-mesh/aic/releases/download/v0.50.12/aic_0.50.12_linux_arm64.tar.gz"
      sha256 "f0da4514bc63f8dc86da95b52f9138a9b58261acfd478a738323d2f072068cb1"

      def install
        bin.install "aic"
        bin.install "aic-session"
        bin.install "aicd"
      end
    end
  end

  def caveats
    <<~EOS
      To run aicd in the background and on login:

        aic daemon install        # writes the right unit for your OS

      First-time setup:
        aic config                # interactive provider/api_key/model wizard
        aic init zsh              # add 'source ~/.aic/hooks.zsh' to your rc
    EOS
  end

  test do
    system "#{bin}/aic", "--version"
    system "#{bin}/aic-session", "--version"
    system "#{bin}/aicd", "--version"
  end
end
