# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gk < Formula
  desc "Lightweight Go git helper CLI (pull, log, status, branch)"
  homepage "https://github.com/x-mesh/gk"
  version "0.41.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/x-mesh/gk/releases/download/v0.41.0/gk_darwin_amd64.tar.gz"
      sha256 "334746acbc56515830dd219ad6eb8f89a33aa70d43b2c0a580483e74a68f2602"

      define_method(:install) do
        bin.install "gk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/x-mesh/gk/releases/download/v0.41.0/gk_darwin_arm64.tar.gz"
      sha256 "8db67700ed6b5a968e58edbd2f872ba9a72877931e4741c86e8e64484604951b"

      define_method(:install) do
        bin.install "gk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/x-mesh/gk/releases/download/v0.41.0/gk_linux_amd64.tar.gz"
      sha256 "2a539db5954fbc997929d5f7a766080582b6795be890e04a61b804088f9df669"
      define_method(:install) do
        bin.install "gk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/x-mesh/gk/releases/download/v0.41.0/gk_linux_arm64.tar.gz"
      sha256 "b6869322010b239e3a25fc4adc4cac1c811e406ac7395bde85863f118ed1623d"
      define_method(:install) do
        bin.install "gk"
      end
    end
  end

  def caveats
    <<~EOS
      gk uses git under the hood. Ensure git >= 2.30 is installed.
    EOS
  end

  test do
    system "#{bin}/gk --version"
  end
end
