# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gk < Formula
  desc "Lightweight Go git helper CLI (pull, log, status, branch)"
  homepage "https://github.com/x-mesh/gk"
  version "0.19.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/x-mesh/gk/releases/download/v0.19.0/gk_0.19.0_darwin_amd64.tar.gz"
      sha256 "9fdf76bae32d14642daca7a33eb1e4ab09e4f30b3485ff027cb7af04fc592877"

      define_method(:install) do
        bin.install "gk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/x-mesh/gk/releases/download/v0.19.0/gk_0.19.0_darwin_arm64.tar.gz"
      sha256 "35d7d73515e5ae859696434448dec1ffa7e1b1e563e72738548fa235e5b889c3"

      define_method(:install) do
        bin.install "gk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/x-mesh/gk/releases/download/v0.19.0/gk_0.19.0_linux_amd64.tar.gz"
      sha256 "793cfe249015311059a62f1f545017d53951009597a8f21541910924c6231e8b"
      define_method(:install) do
        bin.install "gk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/x-mesh/gk/releases/download/v0.19.0/gk_0.19.0_linux_arm64.tar.gz"
      sha256 "453805382c4e3ebdeeeaf7b444c88bb311edfd1f87862d0217a5a50e86716fda"
      define_method(:install) do
        bin.install "gk"
      end
    end
  end

  def caveats
    <<~EOS
      gk uses git under the hood. Ensure git >= 2.30 is installed.
    EOS
  end

  test do
    system "#{bin}/gk --version"
  end
end
