# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gk < Formula
  desc "Lightweight Go git helper CLI (pull, log, status, branch)"
  homepage "https://github.com/x-mesh/gk"
  version "0.41.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/x-mesh/gk/releases/download/v0.41.1/gk_darwin_amd64.tar.gz"
      sha256 "0469d7152392b401bb24a994d05ceaf49b2131a06c4d68971b592c15f598e8c1"

      define_method(:install) do
        bin.install "gk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/x-mesh/gk/releases/download/v0.41.1/gk_darwin_arm64.tar.gz"
      sha256 "776cc54955b3f280228f401ff36f4c654989ada4cec1d694476386736b8db5e6"

      define_method(:install) do
        bin.install "gk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/x-mesh/gk/releases/download/v0.41.1/gk_linux_amd64.tar.gz"
      sha256 "9b86783fa6619399e98efa58fe091c73e2be1cc6b179958b3d961bce6e301cb5"
      define_method(:install) do
        bin.install "gk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/x-mesh/gk/releases/download/v0.41.1/gk_linux_arm64.tar.gz"
      sha256 "7147b1b3afdfcd0e007bac6ce19b3a48c679486fbe4972f64644f9d7ab15451c"
      define_method(:install) do
        bin.install "gk"
      end
    end
  end

  def caveats
    <<~EOS
      gk uses git under the hood. Ensure git >= 2.30 is installed.
    EOS
  end

  test do
    system "#{bin}/gk --version"
  end
end
